* configure.ac: Add --disable-xml option to not look for XML or 	use the XML and XMLSocket AS objects. The default is to support 	XML, since it's part of SWF v6. 	* configure: Regenerated.

diff --git a/trunk/tu-testbed/configure b/trunk/tu-testbed/configure
--- a/trunk/tu-testbed/configure
+++ b/trunk/tu-testbed/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LIBPRE LIBEXT SDL_CONFIG SDL_CFLAGS SDL_LIBS CPP EGREP SDL_MIXER_CFLAGS SDL_MIXER_LIBS OPENGL_CFLAGS OPENGL_LIBS GLUT_LIBS GLU_LIBS HAVE_OPENGL_TRUE HAVE_OPENGL_FALSE ZLIB_CFLAGS ZLIB_LIBS JPEG_CFLAGS JPEG_LIBS PNG_CFLAGS PNG_LIBS LIBXML_CFLAGS LIBXML_LIBS PTHREAD_LIB LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBXML_CFLAGS LIBXML_LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LIBPRE LIBEXT SDL_CONFIG SDL_CFLAGS SDL_LIBS CPP EGREP SDL_MIXER_CFLAGS SDL_MIXER_LIBS OPENGL_CFLAGS OPENGL_LIBS GLUT_LIBS GLU_LIBS HAVE_OPENGL_TRUE HAVE_OPENGL_FALSE ZLIB_CFLAGS ZLIB_LIBS JPEG_CFLAGS JPEG_LIBS PNG_CFLAGS PNG_LIBS PTHREAD_LIB LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -861,6 +861,7 @@ Optional Features:
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
   --enable-pthreads            Enable support for pthreads
+  --disable-xml            Disable support for xml and xmlsocket
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --disable-sdltest       Do not try to compile and run a test SDL program
@@ -869,6 +870,9 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-libxml=PFX   Prefix where libxml++ is installed (optional)
+  --with-libxml-libraries=DIR   Directory where libxml++ library is installed (optional)
+  --with-libxml-includes=DIR   Directory where libxmlc++ header files are installed (optional)
   --with-sdl-prefix=PFX   Prefix where SDL is installed (optional)
   --with-sdl-exec-prefix=PFX Exec prefix where SDL is installed (optional)
   --with-sdl_mixer-incl        directory where sdl_mixer header is
@@ -879,9 +883,6 @@ Optional Packages:
   --with-jpeg-lib         directory where jpeg library is
   --with-png-incl        directory where png header is
   --with-png-lib         directory where png library is
-  --with-libxml=PFX   Prefix where libxml++ is installed (optional)
-  --with-libxml-libraries=DIR   Directory where libxml++ library is installed (optional)
-  --with-libxml-includes=DIR   Directory where libxmlc++ header files are installed (optional)
 
 Some influential environment variables:
   CC          C compiler command
@@ -1926,6 +1927,95 @@ if test x$pthreads = xyes; then
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_PTHREADS
 _ACEOF
+
+fi
+
+# Check whether --enable-libxml or --disable-libxml was given.
+if test "${enable_libxml+set}" = set; then
+  enableval="$enable_libxml"
+  case "${enableval}" in
+  yes) disablexml=yes ;;
+  no)  disablexml=no ;;
+  *)   { { echo "$as_me:$LINENO: error: bad value ${enableval} for disable-xml option" >&5
+echo "$as_me: error: bad value ${enableval} for disable-xml option" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+fi;
+
+if test -z $enable_xml; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBXML
+_ACEOF
+
+
+# Check whether --with-libxml or --without-libxml was given.
+if test "${with_libxml+set}" = set; then
+  withval="$with_libxml"
+  libxml_prefix="$withval"
+else
+  libxml_prefix=""
+fi;
+
+# Check whether --with-libxml-libraries or --without-libxml-libraries was given.
+if test "${with_libxml_libraries+set}" = set; then
+  withval="$with_libxml_libraries"
+  libxml_libraries="$withval"
+else
+  libxml_libraries=""
+fi;
+
+# Check whether --with-libxml-includes or --without-libxml-includes was given.
+if test "${with_libxml_includes+set}" = set; then
+  withval="$with_libxml_includes"
+  libxml_includes="$withval"
+else
+  libxml_includes=""
+fi;
+
+  if test "x$libxml_libraries" != "x" ; then
+    LIBXML_LIBS="-L$libxml_libraries"
+  elif test "x$libxml_prefix" != "x" ; then
+    LIBXML_LIBS="-L$libxml_prefix/lib"
+  elif test "x$prefix" != "xNONE" ; then
+    LIBXML_LIBS="-L$libdir"
+  fi
+
+  if test "x$libxml_includes" != "x" ; then
+    LIBXML_CFLAGS="-I$libxml_includes"
+  elif test "x$libxml_prefix" != "x" ; then
+    LIBXML_CFLAGS="-I$libxml_prefix/include"
+  elif test "$prefix" != "NONE"; then
+    LIBXML_CFLAGS="-I$prefix/include"
+  fi
+
+  echo "$as_me:$LINENO: checking for libxml" >&5
+echo $ECHO_N "checking for libxml... $ECHO_C" >&6
+  no_libxml=""
+
+  if test "x$LIBXML_CFLAGS" = "x" ; then
+    LIBXML_CFLAGS=`pkg-config --cflags libxml-2.0`
+  fi
+
+  if test "x$LIBXML_LIBS" = "x" ; then
+    LIBXML_LIBS=`pkg-config --libs libxml-2.0`
+  fi
+
+  if test "x$LIBXML_CFLAGS" != "x" -a  "x$LIBXML_LIBS" != "x"; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBXML 1
+_ACEOF
+
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+
+
+
 
 fi
 
@@ -6142,76 +6232,6 @@ echo "${ECHO_T}${ac_cv_path_png_lib}" >&6
 
 
 
-
-# Check whether --with-libxml or --without-libxml was given.
-if test "${with_libxml+set}" = set; then
-  withval="$with_libxml"
-  libxml_prefix="$withval"
-else
-  libxml_prefix=""
-fi;
-
-# Check whether --with-libxml-libraries or --without-libxml-libraries was given.
-if test "${with_libxml_libraries+set}" = set; then
-  withval="$with_libxml_libraries"
-  libxml_libraries="$withval"
-else
-  libxml_libraries=""
-fi;
-
-# Check whether --with-libxml-includes or --without-libxml-includes was given.
-if test "${with_libxml_includes+set}" = set; then
-  withval="$with_libxml_includes"
-  libxml_includes="$withval"
-else
-  libxml_includes=""
-fi;
-
-  if test "x$libxml_libraries" != "x" ; then
-    LIBXML_LIBS="-L$libxml_libraries"
-  elif test "x$libxml_prefix" != "x" ; then
-    LIBXML_LIBS="-L$libxml_prefix/lib"
-  elif test "x$prefix" != "xNONE" ; then
-    LIBXML_LIBS="-L$libdir"
-  fi
-
-  if test "x$libxml_includes" != "x" ; then
-    LIBXML_CFLAGS="-I$libxml_includes"
-  elif test "x$libxml_prefix" != "x" ; then
-    LIBXML_CFLAGS="-I$libxml_prefix/include"
-  elif test "$prefix" != "NONE"; then
-    LIBXML_CFLAGS="-I$prefix/include"
-  fi
-
-  echo "$as_me:$LINENO: checking for libxml" >&5
-echo $ECHO_N "checking for libxml... $ECHO_C" >&6
-  no_libxml=""
-
-  if test "x$LIBXML_CFLAGS" = "x" ; then
-    LIBXML_CFLAGS=`pkg-config --cflags libxml-2.0`
-  fi
-
-  if test "x$LIBXML_LIBS" = "x" ; then
-    LIBXML_LIBS=`pkg-config --libs libxml-2.0`
-  fi
-
-  if test "x$LIBXML_CFLAGS" != "x" -a  "x$LIBXML_LIBS" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_LIBXML 1
-_ACEOF
-
-  else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-  fi
-
-
-
-
-
 if test x"$pthreads" = x"yes"; then
   echo "$as_me:$LINENO: checking for main in -lpthread" >&5
 echo $ECHO_N "checking for main in -lpthread... $ECHO_C" >&6
@@ -6982,6 +7002,8 @@ s,@am__untar@,$am__untar,;t t
 s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
 s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
 s,@MAINT@,$MAINT,;t t
+s,@LIBXML_CFLAGS@,$LIBXML_CFLAGS,;t t
+s,@LIBXML_LIBS@,$LIBXML_LIBS,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
 s,@LDFLAGS@,$LDFLAGS,;t t
@@ -7025,8 +7047,6 @@ s,@JPEG_CFLAGS@,$JPEG_CFLAGS,;t t
 s,@JPEG_LIBS@,$JPEG_LIBS,;t t
 s,@PNG_CFLAGS@,$PNG_CFLAGS,;t t
 s,@PNG_LIBS@,$PNG_LIBS,;t t
-s,@LIBXML_CFLAGS@,$LIBXML_CFLAGS,;t t
-s,@LIBXML_LIBS@,$LIBXML_LIBS,;t t
 s,@PTHREAD_LIB@,$PTHREAD_LIB,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
